require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

prepare_react_native_project!

target 'EncryptedStorageExample' do
  config = use_native_modules!

  react_native_path = config[:reactNativePath] || config["reactNativePath"] || File.expand_path('../node_modules/react-native', __dir__)
  use_react_native!(
    :path => react_native_path
  )

  pod 'react-native-encrypted-storage', :path => '../..'
  
  post_install do |installer|
    react_native_post_install(
      installer,
      react_native_path,
      :mac_catalyst_enabled => false
    )
  end
end
